/**
 * Capture a brand-new Riot REST fixture together with a sidecar in the same shape as every
 * committed one (`fixture/source/request/capturedOn/contents/recapture`).
 *
 * This is the tool CLAUDE.md refers to when it says "use `npm run capture` rather than saving a
 * response by hand" — a hand-saved fixture is how the rest_getSchedule.json hl=zh-TW discrepancy
 * went unrecorded for two days. It writes both halves together so a fixture can never exist
 * without the sidecar that makes it re-capturable.
 *
 * For an EXISTING fixture, prefer `npm run capture:refresh <fixture>` instead — it reads the
 * fixture's own recorded `recapture.transform` and reports a shape diff before writing anything.
 * This script always produces a fresh, untrimmed capture with an empty transform; trimming has to
 * be designed and recorded by hand afterwards, the way rest_getTeams.json's was.
 *
 * Usage:
 *   RIOT_ESPORTS_API_KEY=... npm run capture -- getSchedule fixtures/riot-lol/rest_getSchedule_new
 *   RIOT_ESPORTS_API_KEY=... npm run capture -- getSchedule out/sched --leagueId=98767991310872058
 *
 * Nothing here runs at runtime. It is a build-time tool, like the agents that write adapters.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, basename } from 'node:path';

import { apiKeyFromEnv, describeUrl, makeClient, USER_AGENT } from './capture-lib.js';

function usage(message: string): never {
  process.stderr.write(`${message}\n\nusage: npm run capture -- <endpoint> <outPathWithoutExtension> [--key=value ...]\n`);
  process.exit(2);
}

/** Count the rows of whichever top-level collection this endpoint returns, if recognised. */
function countRows(json: unknown): Record<string, number> {
  const out: Record<string, number> = {};
  if (typeof json !== 'object' || json === null) return out;
  const data = (json as { data?: unknown }).data;
  if (typeof data !== 'object' || data === null) return out;
  for (const [key, value] of Object.entries(data as Record<string, unknown>)) {
    if (Array.isArray(value)) out[key] = value.length;
    else if (typeof value === 'object' && value !== null) {
      for (const [k2, v2] of Object.entries(value as Record<string, unknown>)) {
        if (Array.isArray(v2)) out[`${key}.${k2}`] = v2.length;
      }
    }
  }
  return out;
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const positional = argv.filter((a) => !a.startsWith('--'));
  const endpoint = positional[0];
  const outBase = positional[1];
  if (endpoint === undefined || outBase === undefined) usage('endpoint and output path are both required');

  const params: Record<string, string> = {};
  for (const flag of argv.filter((a) => a.startsWith('--'))) {
    const eq = flag.indexOf('=');
    if (eq === -1) usage(`parameter ${flag} needs a value, as --name=value`);
    params[flag.slice(2, eq)] = flag.slice(eq + 1);
  }

  const apiKey = apiKeyFromEnv();
  const client = makeClient(apiKey);
  const capturedAt = new Date().toISOString();
  const res = await client.get(endpoint, params);
  const url = describeUrl(endpoint, params);

  const sidecar = {
    fixture: `${basename(outBase)}.json`,
    source: 'riot-rest-lol',
    request: {
      method: 'GET',
      url,
      queryParams: { hl: 'en-US', ...params },
      pathParams: {},
      headers: {
        'x-api-key': '<public static key, see .env.example RIOT_ESPORTS_API_KEY>',
        'user-agent': USER_AGENT,
        accept: 'application/json',
      },
    },
    capturedOn: capturedAt,
    contents: `Freshly captured, untrimmed. Row counts: ${JSON.stringify(countRows(res.json))}.`,
    recapture: {
      capturable: true,
      endpoint,
      params: { hl: 'en-US', ...params },
      transform: [],
    },
    recaptureNotes: {
      note:
        'This sidecar was generated by capture-fixture.ts and has NOT been reviewed for trimming ' +
        'or personal data. Before committing: check whether the response needs trimming (size, or ' +
        'a personal-data field like players[]), design the transform by hand if so, and re-run ' +
        'capture:refresh to prove the transform reproduces the trimmed file. See fixtures/README.md.',
    },
  };

  await mkdir(dirname(outBase), { recursive: true });
  await writeFile(`${outBase}.json`, `${JSON.stringify(res.json, null, 2)}\n`);
  await writeFile(`${outBase}.meta.json`, `${JSON.stringify(sidecar, null, 2)}\n`);

  process.stdout.write(
    `${outBase}.json      ${String(res.bytes)} bytes\n` +
      `${outBase}.meta.json  ${JSON.stringify(countRows(res.json))}\n` +
      `\nThis fixture is UNTRIMMED and UNREVIEWED. See recaptureNotes in the sidecar before committing.\n`,
  );
}

try {
  await main();
} catch (err) {
  process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
}
